apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie
  namespace: test
  labels:
    app: movie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: movie
    spec:
      containers:
        - image: milchkarton/compose:latest
          imagePullPolicy: Always
          name: movie
          ports:
            - containerPort: 8080
              protocol: TCP
          envFrom:
            - secretRef:
                name: omdb-api-key-secret
            - configMapRef:
                name: movie-configmap
