apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.general.name }}
  namespace: {{ .Release.Name }}
  labels:
    app: {{ .Values.general.name }}
spec:
  {{ if eq .Release.Name "prod" }}
  replicas: 2
  {{ else }}
  replicas: 1
  {{ end }}
  selector:
    matchLabels:
      app: {{ .Values.general.name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: {{ .Values.general.name }}
    spec:
      containers:
        - image: milchkarton/compose:latest
          imagePullPolicy: Always
          name: {{ .Values.general.name }}
          ports:
            - containerPort: 8080
              protocol: TCP
          envFrom:
            - secretRef:
                name: {{ .Values.general.name }}-secrets
            - configMapRef:
                name: {{ .Values.general.name }}-configmap
