---
# Secrets
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.general.name }}-secrets
  namespace: {{ .Release.Name }}
type: Opaque
data:
  OMDB_API_KEY: {{ .Values.omdb.apikey | b64enc }}
---
