---
# Service - for combining multiple pods behind one service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.general.name }}-service
  namespace: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Values.general.name }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
---
