name: Build and Push Image

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  run-maven-build:
    runs-on: ubuntu-latest

    steps:
      # Setup
      - name: Checkout [main] branch
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2.3.1
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      # Maven build
      - name: Build Project with Maven
        run: mvn clean install

      # Docker
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: /home/runner/work/ComposeMovieSpringBoot/ComposeMovieSpringBoot
          push: true
          tags: milchkarton/compose:latest # never use latest. It could contain bugs... 😎
