name: Experiment

on:
  push:
    branches:
      - test

jobs:
  setup-a-file:
    name: Setup and cache a simpel txt file
    runs-on: ubuntu-latest

    steps:
      - name: creating test.txt
        run: |
          cat > ~/text.txt << EOF
            You will never find me!
          EOF

      - name: Print text file
        run: cat ~/text.txt

      - name: Add test.txt to cache
        id: cache-txt-file
        uses: actions/cache@v2
        with:
          path: ~/text.txt
          key: cache-for-workflow-#${{ github.run_number }}

  access-cached-file:
    name: Access cached file from different job
    runs-on: ubuntu-latest
    needs: setup-a-file

    steps:
      - name: Acces Cache
        uses: actions/cache@v2
        with:
          path: ~/text.txt
          key: cache-for-workflow-#${{ github.run_number }}
          restore-keys: cache-for-workflow-

      - name: Try to print the content of the cached file
        run: cat ~/text.txt

