name: Experiment II

on:
  push:
    branches:
      - 'feature-branch-1.**'

jobs:
  say-hello:
    name: Hello
    runs-on: ubuntu-latest

    steps:
      - name: say hello
        run: echo hello
